### ISSUE TITLE
[CI/CD] Windows update sha512 case error

### ISSUE THREAD

**Issue by BrettCleary** [HyperPlay-Gaming/hyperplay-desktop-client#645]
The latest.yml file is being generated as following
```
files:
- size: 188289376
  url: HyperPlay-0.9.0-Setup-x64.exe
  sha512: 7DC4E9B2429F31B79C41F17FECF0CE7058C37E10B38D3D3655140D0043874E692606D6E27F4AB1006C69E8A6CBF0A6607852AEC8982EBA39900946654038C40B
path: HyperPlay-0.9.0-Setup-x64.exe
version: 0.9.0
sha512: 7dc4e9b2429f31b79c41f17fecf0ce7058c37e10b38d3d3655140d0043874e692606d6e27f4ab1006c69e8a6cbf0a6607852aec8982eba39900946654038c40b
releaseDate: 2023-11-17T20:30:50.391Z
```

which gives this error when auto updating
![image](https://github.com/HyperPlay-Gaming/hyperplay-desktop-client/assets/27568879/e43f3243-71fe-48c2-a85c-94abc5fc9df3)

After changing it to the following, auto-updating successfully completes
```
files:
- size: 188289376
  url: HyperPlay-0.9.0-Setup-x64.exe
  sha512: 7dc4e9b2429f31b79c41f17fecf0ce7058c37e10b38d3d3655140d0043874e692606d6e27f4ab1006c69e8a6cbf0a6607852aec8982eba39900946654038c40b
path: HyperPlay-0.9.0-Setup-x64.exe
version: 0.9.0
sha512: 7dc4e9b2429f31b79c41f17fecf0ce7058c37e10b38d3d3655140d0043874e692606d6e27f4ab1006c69e8a6cbf0a6607852aec8982eba39900946654038c40b
releaseDate: 2023-11-17T20:30:50.391Z
```
